<a href="https://colab.research.google.com/github/Shaon007/EDGEpractice-IT20055/blob/main/EDGEpractice31_Oct(IT20055).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy Test

In [ ]:
import numpy as np
!pip install numpy


In [3]:
import numpy as np

test2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

test2d.shape


(3, 3)

In [5]:
test2d.ndim

2

In [6]:
test2d.size

9

In [8]:
test_3d = np.array([[[1, 2, 3], [5, 6, 7], [9, 10, 11]], [[13, 14, 15], [17, 18, 19], [21, 22, 23]]])

test_3d.shape



(2, 3, 3)

In [10]:
test_3d[1]

array([[13, 14, 15],
       [17, 18, 19],
       [21, 22, 23]])

In [11]:
array_1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array_2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

product = array_1 * array_2
print(" product:\n", product)


 product:
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]
